# Generated by Django 4.2.5 on 2023-09-22 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisciplineEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TaskEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('date_delivery', models.DateField()),
                ('concluded', models.BooleanField(default=True)),
                ('discipline', models.ManyToManyField(to='school.disciplineentity')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.studententity')),
            ],
        ),
    ]
